# docker-compose.yml
version: "3.7"
services:
  jenkins:
    #the container name
    image: jenkinsci/blueocean
    
    privileged: true
    
    user: root
    
    ports:
      - 8080:8080
      - 50003:50000
    volumes:
      - ${PWD}/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins.install.runSetupWizard=false
